on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

name: build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Clone matsim-melbourne/example-project
      uses: actions/checkout@v2
      with:
        repository: matsim-melbourne/example-project
        path: example-project

    - name: Build with Maven
      run: cd example-project && mvn clean package
